README.md, bioptim/__init__.py, bioptim/gui/plot.py, bioptim/interfaces/SolverOptions.py, bioptim/misc/enums.py, bioptim/optimization/optimal_control_program.py, bioptim/optimization/solution.py, tests/test_simulate.py, tests/utils.py
Related to #401 
1. [] Does your submission pass the tests (if not please explain why this is intended)?
=> Add the choice for an integrator of the solution

bioptim/gui/plot.py, bioptim/optimization/optimal_control_program.py
I don't think it should be merged since it is really a patch and not a fix.
But this way it is available to others, in the mean time :)
=> Ignored plots for phase_transition

bioptim/dynamics/configure_problem.py
1. [x] Does your submission pass the tests (if not, please explain why this is intended)?
2. [x] Did you write proper documentation (docstrings and ReadMe)
This PR is merely intended for custom dynamics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/454)
=> Allow the user to not expand the dynamics if wanted

README.md, bioptim/__init__.py, bioptim/examples/getting_started/pendulum.py, bioptim/gui/graph.py, bioptim/gui/plot.py, bioptim/interfaces/acados_interface.py, bioptim/interfaces/ipopt_interface.py, bioptim/limits/objective_functions.py, bioptim/limits/penalty.py, bioptim/limits/penalty_option.py, bioptim/misc/enums.py, bioptim/optimization/optimal_control_program.py, bioptim/optimization/optimization_vector.py, bioptim/optimization/solution.py, tests/test_cost_function_integration.py, tests/test_penalty.py
related to #416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/458)
=> Readme update and trapezoidal integration of cost function

bioptim/gui/graph.py
#450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/461)
=> print bounds of controls and states 

README.md, bioptim/__init__.py, bioptim/limits/path_conditions.py, bioptim/limits/penalty.py
2. [x] Did you write proper documentation (docstrings and ReadMe)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/466)
=> Playing with qddot 

bioptim/optimization/optimal_control_program.py
very small fix to handle the plot when there is a target with only one value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/467)
=> small fix manage unit target

README.md, bioptim/__init__.py, bioptim/gui/graph.py, bioptim/limits/path_conditions.py, bioptim/limits/penalty.py, bioptim/optimization/optimal_control_program.py, bioptim/optimization/solution.py, tests/test_penalty.py, tests/test_simulate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/464)
=> merge master into crazydynamics

.gitignore, README.md, bioptim/dynamics/configure_problem.py, bioptim/dynamics/dynamics_functions.py, bioptim/examples/getting_started/example_joints_acceleration_driven.py, bioptim/examples/getting_started/models/double_pendulum.bioMod, environment.yml, tests/test_dynamics.py
Related to #487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/488)
=> [RTM] Free floating dynamics

bioptim/dynamics/configure_problem.py
Small fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/505)
=> [RTM] qddot as statedot

bioptim/dynamics/configure_problem.py, bioptim/dynamics/dynamics_functions.py, bioptim/examples/acados/pendulum.py, bioptim/examples/acados/static_arm.py, bioptim/examples/fatigue/pendulum_with_fatigue.py, bioptim/examples/fatigue/static_arm_with_fatigue.py, bioptim/examples/getting_started/custom_phase_transitions.py, bioptim/examples/getting_started/example_implicit_dynamics.py, bioptim/examples/getting_started/example_multinode_constraints.py, bioptim/examples/getting_started/example_save_and_load.py, bioptim/examples/moving_horizon_estimation/cyclic_nmpc.py, bioptim/examples/moving_horizon_estimation/multi_cyclic_nmpc.py, bioptim/examples/muscle_driven_ocp/muscle_activations_tracker.py, bioptim/examples/muscle_driven_ocp/muscle_excitations_tracker.py, bioptim/examples/muscle_driven_ocp/static_arm_with_contact.py, bioptim/interfaces/acados_interface.py, bioptim/interfaces/solver_options.py, bioptim/limits/constraints.py, bioptim/optimization/solution.py, tests/test_dynamics.py, tests/test_global_getting_started.py
- blacked
- all tests works
- implicit muscle driven handled with rigidbody dynamics enum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/490)
=> [RTM] Pull master in crazydynamics

bioptim/interfaces/acados_interface.py, tests/test_acados_interface.py
* [ x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
3. [] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?
* [x ] Have you written new tests for your core changes, as applicable?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> [RTM] Mayer on first node with acados

bioptim/dynamics/dynamics_functions.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/515)
=> [RTR] implicit defect works in torque driven.

bioptim/dynamics/configure_problem.py, bioptim/dynamics/dynamics_functions.py, bioptim/optimization/optimal_control_program.py
related to #523
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/524)
=> [RTR] Names of variables in figures handles variable mapping

bioptim/dynamics/integrator.py, bioptim/dynamics/ode_solver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/529)
=> [RTR] scoot docstrings

bioptim/optimization/solution.py, tests/test_cost_function_integration.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/546)
=> [RTR] integration rule tested in collocation

.gitignore, README.md, bioptim/__init__.py, bioptim/examples/getting_started/example_multistart.py, bioptim/examples/torque_driven_ocp/trampo_quaternions.py, bioptim/limits/penalty.py, bioptim/optimization/multi_start.py, tests/test_global_getting_started.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/555)
=> Multi-start module

bioptim/gui/plot.py
* [ x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ x] Have you opened/linked the issue related to your pull request? issue #543
* [ x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ x] When ready to merge, have you sent a comment pinging @pariterre in it?
3. [x ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?
- - -
This change is [<img …
=> [RTR] correction of graphs for mapped tau

bioptim/examples/moving_horizon_estimation/mhe.py, bioptim/interfaces/solve_ivp_interface.py, bioptim/optimization/receding_horizon_optimization.py, bioptim/optimization/solution.py, tests/test_global_mhe.py, tests/test_mhe.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/592)
=> [RTR] split final MHE save

bioptim/dynamics/configure_problem.py, bioptim/examples/muscle_driven_ocp/muscle_activations_tracker.py, bioptim/examples/muscle_driven_ocp/muscle_excitations_tracker.py, bioptim/interfaces/solve_ivp_interface.py
related to #593 i think so.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/597)
=> Fix variable naming

setup.py
related to #601
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/602)
=> setup install fix

bioptim/interfaces/biorbd_model.py, tests/test_biorbd_model.py
add an error if the type of the model path is not correct + new example to test model path type
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/605)
=> [RTM] add error for model path type

bioptim/optimization/optimal_control_program.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/617)
=> [RTR] prevents further errors in inital guess size

bioptim/interfaces/biorbd_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/645)
=> [RTM] Work around for the memory leak in the meantime

README.md, bioptim/limits/penalty.py, tests/test_penalty.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/646)
=> [RTM] Added intercept for proportional states/controls

.github/workflows/run_tests.yml, bioptim/examples/inverse_optimal_control/double_pendulum_torque_driven_IOCP.py, bioptim/optimization/optimization_vector.py, bioptim/optimization/parameters.py, environment.yml, tests/test_dynamics.py, tests/test_ligaments.py, tests/test_passive_torque.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/660)
=> Fix for Casadi 3.6.2 on Mac

bioptim/dynamics/configure_problem.py, bioptim/dynamics/dynamics_functions.py, bioptim/dynamics/ode_solver.py, bioptim/examples/muscle_driven_ocp/muscle_activations_tracker.py, bioptim/examples/muscle_driven_ocp/muscle_excitations_tracker.py, bioptim/interfaces/interface_utils.py, bioptim/limits/penalty_option.py, bioptim/optimization/non_linear_program.py, bioptim/optimization/optimization_variable.py, bioptim/optimization/optimization_vector.py, bioptim/optimization/solution.py, tests/test_controltype_none.py, tests/test_penalty.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/663)
=> Replaced state["scaled"] by state.scaled

bioptim/interfaces/interface_utils.py
I think I fixed the issue #620
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/670)
=> [RTR] bug with derivative=True and node=Node.ALL

bioptim/limits/path_conditions.py, bioptim/misc/options.py
Corrects a bug when running `getting_started\pendulum.py` and check the bound is not defined twice or with the same name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/703)
=> [RTM] Bug and BoundsList

bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle.py, bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle_excitations.py, bioptim/interfaces/biomodel.py, bioptim/interfaces/biorbd_model.py, bioptim/optimization/solution.py, tests/test_all_examples.py, tests/test_global_torque_driven_ocp.py, tests/test_simulate.py
addressing pyomeca/bioviz/issues/94
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/714)
=> [RTR] some little test on preparing the data for animation of tracked markers.

tests/test_solver_options.py
[tracking tests on Ipopt options following](https://github.com/pyomeca/bioptim/pull/723/commits/ddfdaa138752eb818964fdcb5de3c5828f0f4a04) https://github.com/pyomeca/bioptim/pull/715 
[ddfdaa1](https://github.com/pyomeca/bioptim/pull/723/commits/ddfdaa138752eb818964fdcb5de3c5828f0f4a04)
to have no more surprises https://github.com/pyomeca/bioptim/issues/706
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/723)
=> [RTR] solver options ipopt test

bioptim/examples/getting_started/pendulum.py, bioptim/optimization/optimal_control_program.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/724)
=> [RTM] Restoring bounds on graphs

tests/test_plot_show_bounds.py
tiny test following #716 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/728)
=> [RTM] show bounds test in ocp

bioptim/examples/getting_started/custom_plotting.py, bioptim/gui/plot.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/767)
=> Fixed custom_plot

bioptim/interfaces/solver_options.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/788)
=> [RTR] Solving a critical issue of codeclimate

bioptim/optimization/solution.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/787)
=> [RTR] Try to refactor a bit the initialisation of Solution

bioptim/dynamics/integrator.py, bioptim/dynamics/ode_solver.py, bioptim/examples/stochastic_optimal_control/obstacle_avoidance_direct_collocation.py, bioptim/limits/penalty.py, bioptim/optimization/optimal_control_program.py, bioptim/optimization/solution/simplified_objects.py, bioptim/optimization/stochastic_optimal_control_program.py
While refactoring this weekend, including_starting_collocation_point seemed hard to understand for me. 
I propose renaming :
"duplicate_collocation_starting_point" which emphasize more what it does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/796)
=> [RTR] duplicate_collocation_starting_point

bioptim/examples/getting_started/pendulum.py, bioptim/optimization/solution/solution.py, environment.yml, tests/shard3/test_global_getting_started.py
Answers to issue #805
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/806)
=> [RTM] Added the commit ID + version to sol

README.md, bioptim/examples/getting_started/pendulum_constrained_states_controls.py, bioptim/limits/constraints.py, tests/shard1/test_all_examples.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/817)
=> [RTR] Add state and control bounds using constraints

bioptim/examples/custom_model/custom_package/my_model.py, bioptim/examples/custom_model/main.py, tests/shard1/test_all_examples.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/822)
=> Fix on custom_model.py + test

bioptim/examples/getting_started/example_simulation.py
As said in the title
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/823)
=> fix: restore example simulation in getting started

bioptim/limits/constraints.py, bioptim/limits/penalty.py, bioptim/optimization/variable_scaling.py, tests/shard5/test_global_stochastic_collocation.py, tests/shard6/test_global_stochastic_except_collocation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/842)
=> [RTM?] SOCP collocation scaling

bioptim/models/biorbd/biorbd_model.py, bioptim/models/biorbd/holonomic_biorbd_model.py
Light PR, only updating docstrings while reading the holonomic biorbd model
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/847)
=> doc(biorbd_holonomic_model)

bioptim/dynamics/configure_problem.py, bioptim/dynamics/dynamics_functions.py, bioptim/limits/penalty.py, bioptim/limits/penalty_option.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/851)
=> [RTR] Fixing target plots

bioptim/examples/getting_started/example_continuity_as_objective.py, tests/shard1/test_continuity_as_objective.py
Todo:
- Remove MINIMIZE TIME from the example and test in 3.1 and 3.2
- Get the results in 3.1 version from #825
- Verify we get the same in version 3.2
- Merge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/826)
=> [RTR] FIX: example which had an unexpected behavior, and a new that new implementation should pass

bioptim/dynamics/integrator.py
3 lines, nothing much
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/861)
=> [RTR] catching when reading

bioptim/interfaces/solve_ivp_interface.py, bioptim/optimization/solution/solution.py, tests/shard4/test_simulate.py, tests/shard6/test_global_stochastic_except_collocation.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/859)
=> [RTR] Fix sol.integrate shooting.single continuity

bioptim/dynamics/configure_problem.py, bioptim/dynamics/fatigue/fatigue_dynamics.py, bioptim/gui/graph.py, bioptim/interfaces/acados_interface.py, bioptim/limits/constraints.py, bioptim/limits/multinode_penalty.py, bioptim/limits/objective_functions.py, bioptim/limits/path_conditions.py, bioptim/limits/penalty.py, bioptim/limits/penalty_option.py, bioptim/limits/phase_transition.py, bioptim/misc/mapping.py, bioptim/misc/options.py, bioptim/models/biorbd/biorbd_model.py, bioptim/optimization/optimal_control_program.py, bioptim/optimization/solution/solution.py, tests/shard4/test_penalty.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/865)
=> [RTM] external forces as symbolic variables to allow multi-threading

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/873)
=> [RTR] very small doc addition

bioptim/dynamics/configure_problem.py, bioptim/gui/plot.py, bioptim/optimization/optimal_control_program.py
@SamHybz, @AnaisFarr 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/885)
=> holonomic graph multiphase multi all combinations

bioptim/gui/plot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/890)
=> Removed useless recomputing of yticks

bioptim/examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle.py, bioptim/limits/constraints.py, bioptim/limits/objective_functions.py, bioptim/limits/penalty.py, bioptim/models/biorbd/multi_biorbd_model.py, tests/shard4/test_penalty.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/891)
=> [RTR] contact force at the end of interval for takeoff

bioptim/models/biorbd/viewer_pyorerun.py, bioptim/models/biorbd/viewer_utils.py, tests/shard3/test_global_torque_driven_ocp.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/896)
=> feat: tracked markers displayed with pyorerun

bioptim/examples/moving_horizon_estimation/multi_cyclic_nmpc_with_parameters.py, bioptim/examples/torque_driven_ocp/example_pendulum_time_dependent.py, bioptim/optimization/receding_horizon_optimization.py, tests/shard2/test_global_nmpc_final.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/894)
=> [RTM when corrected] Enabling parameters in receding horizon

bioptim/dynamics/configure_problem.py, bioptim/dynamics/dynamics_functions.py
TODO
TODO
TODO
Also my formatter configuration seems different, will fix this in a next commit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/910)
=> [WIP] Added with_friction support for muscle driven dynamics. Ported funtionalities from torque driven dynamics

bioptim/models/biorbd/biorbd_model.py
It seems to me that the set_friction_coefficients function is incorrectly implemented as it returns the parameter instead of changing it. This PR fixes that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/913)
=> Fixing error in set_friction_coefficients

bioptim/misc/options.py, bioptim/optimization/non_linear_program.py, bioptim/optimization/optimal_control_program.py, tests/shard1/test_prepare_all_examples.py, tests/shard4/test_update_bounds_and_init.py, tests/shard4/test_variable_time.py
- The checks of ode solvers were not allowing to use different solvers for each phase. Added a test to preserve that feature.
- The bounds of algebraic states were not multiphase.
- Assuming bounds are the same over every phase when length of a BoundList =1 made clear by refactoring, 
Essentially, I'm preparing the field for bounds not defined for different phases. I have a problem where algebraic states bounds existing only on 3/5 phases.
Sub-step for #907, to decrease the cognitive load of the review. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/914)
=> [RTR] Refactor and fixing bugs - list of OdeSolvers, multiphase algebraic states bounds and not on every phases.

README.md
@EveCharbie is that clearer ?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/923)
=> Update README.md - Variable scaling

bioptim/dynamics/configure_problem.py, bioptim/examples/torque_driven_ocp/example_soft_contact.py, bioptim/limits/penalty.py, bioptim/limits/penalty_option.py, tests/shard2/test_cost_function_integration.py, tests/shard3/test_get_time_solution.py, tests/shard4/test_soft_contacts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/935)
=> [RTR] deleted the lines that should have been deleted

bioptim/examples/getting_started/custom_parameters.py, bioptim/examples/getting_started/example_parameter_scaling.py, bioptim/examples/getting_started/models/pendulum_wrong_gravity.bioMod, bioptim/interfaces/interface_utils.py, bioptim/models/biorbd/biorbd_model.py, bioptim/optimization/parameters.py, tests/shard6/test_param_obj_and_scaling.py
I've built an example on top of your example @EveCharbie. The Idea is to have an objective with the parameter in it to see it evolve through the iterations of IPOPT, to see if the sol output is the same as the one of IPOPT.
While I had only one objective, the objective was not taken into account. I manage to do a quick fix, with no ideas of the consequences. Some choices may have some rational and need to be discussed in the next PR Review @pariterre 
@p-shg, you can build on top of this PR to see through ipopt how the scaling affect the parameter.
On top of :
- #929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/930)
=> [RTR/RTM] fix: parameter objective need parameters decision variables in any scenario right ?

bioptim/dynamics/fatigue/effort_perception.py, bioptim/dynamics/fatigue/fatigue_dynamics.py, bioptim/dynamics/fatigue/michaud_fatigue.py, bioptim/dynamics/fatigue/muscle_fatigue.py, bioptim/dynamics/fatigue/tau_fatigue.py, bioptim/dynamics/fatigue/xia_fatigue.py, bioptim/misc/parameters_types.py
https://github.com/pyomeca/bioptim/pull/975
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/977)
=> [RTM] Fully converted dynamics fatigue to new types

bioptim/gui/online_callback_abstract.py, bioptim/gui/online_callback_multiprocess.py, bioptim/gui/online_callback_server.py, bioptim/gui/plot.py, bioptim/gui/serializable_class.py, bioptim/interfaces/interface_utils.py, bioptim/misc/parameters_types.py
https://github.com/pyomeca/bioptim/issues/927
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/975)
=> [RTR]Convert gui to new types

README.md
Tried the pendulum example given and didn't work ; Replaced x_bounds["dot"] by x_bounds["qdot"] like it was written on the tutorial just before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/992)
=> [RTR] Corrected variable name in pendulum example of ReadMe

bioptim/examples/holonomic_constraints/custom_dynamics.py
Refines the descriptions of the holonomic constraint functions to better reflect their purpose and usage within the solver.
- Explains that holonomic constraints are added directly to the solver's constraint set, rather than being embedded in the equations of motion.
- Details the purpose of the end node constraint function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/989)
=> [RTM] docs: holonomic constraints in the solver within an example
