- biorbd_optim/penalty.py
- biorbd_optim/variable_optimization.py
- examples/align/align_marker_on_segment.py
- examples/align/align_segment_on_rt.py
- examples/align/cube_and_line.bioMod
- tests/test_align.py
align_marker_on_segment dosen't work with collocation with pytest (but ok with original file)
> Adds a directory align with 2 examples/tests

- biorbd_optim/dynamics.py
- biorbd_optim/optimal_control_program.py
- biorbd_optim/plot.py
- biorbd_optim/problem_type.py
- biorbd_optim/variable_optimization.py
- examples/torque_driven_with_contact/contact_forces_inequality_constraint.py
- examples/torque_driven_with_contact/maximize_predicted_height_CoM.py
- examples/torque_driven_with_contact/non_slipping_constraint.py
For new plots like contact forces display
> [WIP] New keys nbContact and additional_plots for new plots

- biorbd_optim/dynamics.py
- biorbd_optim/problem_type.py
- examples/muscle_driven_ocp/muscle_activations_tracker.py
- examples/muscle_driven_ocp/muscle_excitations_tracker.py
- tests/test_muscle_tracking.py
- tests/test_plots.py
Add foward dynamics without residual torques and modify the tracking example with option residual_torques true or false.
> Activation control

- biorbd_optim/dynamics.py
- biorbd_optim/problem_type.py
- examples/muscle_driven_ocp/static_arm_with_contact.py
- examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle.py
- examples/muscle_driven_with_contact/muscle_activations_contacts_tracker.py
- tests/test_muscle_driven_ocp.py
match the names of the other functions
> Changed name for muscle activation and torque driven with contact

- .gitignore
- biorbd_optim/optimal_control_program.py
- examples/getting_started/pendulum.py
- tests/utils.py
I also add a difference between ".bo" = sol + ocp and ".bbo" = get_data (inter alia ready to use with biorbdviz -> this is why i add a second "b"), best idea ??
> Short function to print context of problem in a ".bo" and new extension ".bbo"

- biorbd_optim/penalty.py
- examples/align/align_and_minimize_marker_velocity.py
- examples/align/cube_and_line.bioMod
- tests/test_minimize_marker_velocity.py
> Select referential in which minimize_markers_displacement is expressed

- biorbd_optim/__init__.py
- biorbd_optim/optimal_control_program.py
- biorbd_optim/problem_type.py
> problem_type : Regroups the addition of the muscles in configure_muscles

- biorbd_optim/penalty.py
2. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120`)?
> Fixed plot in minimize_states

- biorbd_optim/limits/path_conditions.py
- biorbd_optim/misc/optimal_control_program.py
- biorbd_optim/misc/options_lists.py
- biorbd_optim/misc/parameters.py
- tests/test_penalty.py
- tests/test_update.py
- tests/test_update_bounds_and_init.py
> Implement initial guess in the same way as update_objectives, update_constraints, etc.

- bioptim/misc/optimal_control_program.py
> Fix error in multiphase with q_mapping in __add_to_nlp

- bioptim/interfaces/acados_interface.py
Update u_bounds in init_and_update function
> Fix acados_interface bug

- bioptim/dynamics/problem.py
* [NA] Have you opened/linked the issue related to your pull request?
> Separated configure_q_qdot 

- bioptim/limits/penalty.py
- tests/test_penalty.py
> [WIP] Add non linear bound for custom constraints

- bioptim/interfaces/acados_interface.py
- examples/muscle_driven_with_contact/contact_forces_inequality_constraint_muscle.py
- examples/muscle_driven_with_contact/muscle_activations_contacts_tracker.py
- tests/test_global_minimize_marker_velocity.py
- tests/test_global_muscle_tracking.py
> Added Mayer target handling when recursive call to acados solver

- examples/getting_started/external_forces_with_custom_dynamics.py
- examples/getting_started/mass_point.bioMod
* [NA] Have you opened/linked the issue related to your pull request?
* [] When ready to merge, have you sent a comment pinging @pariterre in it?
> Added Example for External forces (in function of states)

- bioptim/interfaces/acados_interface.py
- tests/test_acados_interface.py
> Added Linear_LS handling in acados

- tests/test_global_optimal_time.py
- tests/test_penalty.py
> Some tests weren't passing on certain CPU

- bioptim/gui/plot.py
> Correct bug plot when number of contact forces increases with phases

- bioptim/interfaces/ipopt_interface.py
- bioptim/misc/optimal_control_program.py
> Add parameters and lagrange multipliers initialisation for warm-start

- README.md
> [WIP] Update README.md up to ### Class: NonLinearProgram

- README.md
> Added HSL in Readme

- bioptim/interfaces/acados_interface.py
- bioptim/interfaces/ipopt_interface.py
- bioptim/optimization/solution.py
> Add sol.cost computation for acados

- README.md
> Added a table of contents in the ReadMe

- bioptim/interfaces/ipopt_interface.py
> This is an omission from previous PR: added inf_pr and inf_du in ipopt_interface

- README.md
> Update citation in readme

- README.md
> Update link to biorxiv preprint

- bioptim/limits/penalty.py
> Added nlp in call to add_to_penalty, when get_all_nodes_at_once == True. Otherwise, ObjectiveFunction.add_to_penalty would fail

- bioptim/dynamics/dynamics_functions.py
> Add dispatch_q_qdot() function

- external/acados_install_mac.sh
> added script for acados install on mac

- bioptim/limits/penalty.py
> Move a comment

- bioptim/interfaces/acados_interface.py
> Restore option setter in acados

- README.md
- bioptim/dynamics/problem.py
- bioptim/limits/penalty.py
- bioptim/misc/enums.py
- tests/test_penalty.py
> Added penultimate node and integrated plot for contact forces

- bioptim/gui/graph.py
- tests/test_graph.py
> Fix minor bugs

- README.md
> Updated readme including graphviz dependency

- bioptim/gui/graph.py
> Added control type in graph

- bioptim/interfaces/acados_interface.py
- examples/muscle_driven_ocp/muscle_activations_tracker.py
* [ x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ x] Have you opened/linked the issue related to your pull request?
* [x ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
3. [ x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?
> Reshape objectives function to match Acados cost function dim

- bioptim/__init__.py
- bioptim/misc/casadi_expand.py
> Added a smooth if_else to replace casadi's one

- bioptim/dynamics/ode_solver.py
- bioptim/limits/penalty.py
- bioptim/optimization/optimal_control_program.py
- bioptim/optimization/solution.py
> CVODES update

- bioptim/interfaces/SolverOptions.py
> bug fix when using show_options

- external/acados_install_linux.sh
- external/acados_install_mac.sh
Added also right way to find max number of CPU for linux
> Fix issue for acados compilation

- bioptim/dynamics/configure_problem.py
> update docstring of configure_problem.py

- bioptim/interfaces/biorbd_interface.py
- bioptim/limits/constraints.py
> now handling parameter optimisation with implicit dynamics such as time.

- bioptim/dynamics/configure_problem.py
- tests/test_dynamics.py
> Handling multiphase problems with implicit dynamics

- bioptim/limits/constraints.py
- bioptim/misc/utils.py
- bioptim/optimization/optimal_control_program.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/460)
> checking version for article fix

- README.md
- bioptim/__init__.py
- bioptim/dynamics/configure_problem.py
- bioptim/dynamics/dynamics_functions.py
- bioptim/examples/getting_started/example_implicit_dynamics.py
- bioptim/examples/getting_started/pendulum.py
- bioptim/examples/torque_driven_ocp/example_soft_contact.py
- bioptim/examples/torque_driven_ocp/maximize_predicted_height_CoM.py
- bioptim/gui/graph.py
- bioptim/gui/plot.py
- bioptim/interfaces/acados_interface.py
- bioptim/interfaces/biorbd_interface.py
- bioptim/interfaces/ipopt_interface.py
- bioptim/limits/constraints.py
- bioptim/limits/objective_functions.py
- bioptim/limits/penalty.py
- bioptim/limits/penalty_option.py
- bioptim/misc/__version__.py
- bioptim/misc/enums.py
- bioptim/optimization/optimal_control_program.py
- bioptim/optimization/solution.py
- environment.yml
- tests/test__global_plots.py
- tests/test_cost_function_integration.py
- tests/test_dynamics.py
- tests/test_global_torque_driven_with_contact_ocp.py
- tests/test_penalty.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/426)
> Semi-explicit and rigid contacts

- bioptim/dynamics/configure_problem.py
found thanks to the tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/463)
> fixing an error because of merge

- bioptim/limits/penalty.py
- tests/test_penalty.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/469)
> minimize comddot without qddot as variable

- bioptim/gui/plot.py
- bioptim/optimization/optimal_control_program.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/470)
> Multinode Constraint Plot

- bioptim/gui/plot.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/473)
> changed len to shape

- README.md
- bioptim/gui/plot.py
- bioptim/limits/multinode_constraint.py
- bioptim/limits/penalty.py
- bioptim/optimization/optimal_control_program.py
- tests/test_multinode_constraints.py
- tests/test_penalty.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/474)
> merge master into crazy dynamics

- bioptim/examples/moving_horizon_estimation/cyclic_nmpc.py
- bioptim/examples/moving_horizon_estimation/multi_cyclic_nmpc.py
- bioptim/examples/muscle_driven_ocp/static_arm_with_contact.py
related to #468
@pariterre
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/475)
> tested examples

- bioptim/examples/acados/pendulum.py
- bioptim/examples/acados/static_arm.py
- bioptim/examples/fatigue/pendulum_with_fatigue.py
- bioptim/examples/fatigue/static_arm_with_fatigue.py
- bioptim/examples/getting_started/custom_phase_transitions.py
- bioptim/examples/getting_started/example_implicit_dynamics.py
- bioptim/examples/getting_started/example_multinode_constraints.py
- bioptim/examples/getting_started/example_save_and_load.py
print() function replaced by print_cost()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/476)
> fixed examples

- bioptim/optimization/solution.py
Small pull request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/482)
> more info in detailed_cost

- bioptim/optimization/solution.py
- tests/test_global_getting_started.py
Very small commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/484)
> States without intermediate states in case of collocation

- bioptim/examples/__main__.py
- bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_bounds.py
- bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_mapping.py
- tests/test_all_examples.py
This change is far from crutial, it can be discarded if not desirable.
@pariterre please tell me if you'd like that (so that I fix the tests accordingly)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/481)
> [RTR] changed the example to match symmetry_by_mapping/constraint

- bioptim/dynamics/configure_problem.py
- bioptim/gui/plot.py
- bioptim/limits/path_conditions.py
- bioptim/optimization/non_linear_program.py
- bioptim/optimization/optimal_control_program.py
- tests/test_dynamics.py
related to issue : plots with different nx/nu #341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/483)
> [RTM] graphs uneven number of variables

- bioptim/limits/constraints.py
Very small commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/497)
> track qddot as constraint

- bioptim/dynamics/ode_solver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/498)
> defecttype on other ode solvers

- bioptim/limits/penalty.py
- bioptim/optimization/solution.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/495)
> [RTM?] Detailed cost dimension bug for markers target

- bioptim/limits/constraints.py
- bioptim/optimization/solution.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/500)
related to #455
> [RTM] animated tracked markers

- bioptim/examples/acados/pendulum.py
Replace the last PR #503.
To respond to the issue #407
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/508)
> [RTR] Change pendulum acados example for more realistic results

- bioptim/examples/acados/pendulum.py
- bioptim/interfaces/solver_options.py
To respond to the issue #493.
* [ x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x ] When ready to merge, have you sent a comment pinging @pariterre in it?
1. [ x] Does your submission pass the tests (if not please explain why this is intended)?
3. [ x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/502)
> [RTM] Change solver option set and turn back to the initial set convergence. 

- bioptim/limits/penalty_option.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/511)
> [RTR] Shape bug when the index list contains only one index

- bioptim/dynamics/configure_problem.py
- bioptim/limits/constraints.py
- bioptim/limits/multinode_constraint.py
- bioptim/limits/objective_functions.py
- bioptim/limits/penalty.py
- bioptim/limits/penalty_option.py
- bioptim/limits/phase_transition.py
- bioptim/misc/fcn_enum.py
- tests/test_penalty.py
This allow for better input validation of custom function.
It could also serve a base for #496 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/512)
> [RTR] Better fcn enum

- .gitignore
- README.md
- bioptim/__init__.py
- bioptim/dynamics/configure_problem.py
- bioptim/dynamics/dynamics_functions.py
- bioptim/examples/__main__.py
- bioptim/examples/acados/pendulum.py
- bioptim/examples/getting_started/custom_initial_guess.py
- bioptim/examples/getting_started/example_joints_acceleration_driven.py
- bioptim/examples/getting_started/models/double_pendulum.bioMod
- bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_bounds.py
- bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_mapping.py
- bioptim/gui/plot.py
- bioptim/interfaces/acados_interface.py
- bioptim/interfaces/solver_options.py
- bioptim/limits/constraints.py
- bioptim/limits/path_conditions.py
- bioptim/limits/penalty.py
- bioptim/optimization/non_linear_program.py
- bioptim/optimization/optimal_control_program.py
- bioptim/optimization/solution.py
- environment.yml
- tests/test_acados_interface.py
- tests/test_all_examples.py
- tests/test_dynamics.py
- tests/test_global_getting_started.py
- tests/test_update_bounds_and_init.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/514)
> [RTR] master merged into CrazyDynamics to mare sure everything fits

- bioptim/optimization/solution.py
added some docstrings to help the readability
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/522)
> [RTR] scoot some documentation

- bioptim/dynamics/dynamics_functions.py
- bioptim/gui/plot.py
- bioptim/limits/penalty.py
- bioptim/optimization/optimal_control_program.py
related to #447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/513)
> [RTM] continuity constraints are well displayed

- .appveyor.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/526)
> [RTM] Check black earlier in the build to save some time

- README.md
- bioptim/optimization/optimal_control_program.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/535)
> [RTR] readme update (do not use .bo)

- bioptim/optimization/optimal_control_program.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/539)
> Made the error message even better!

- bioptim/limits/objective_functions.py
- bioptim/limits/penalty.py
- tests/test_penalty.py
related to #497 finalize the use of this penalty.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/528)
> [RTR] MinimizeQDDOT

- bioptim/dynamics/dynamics_functions.py
- bioptim/dynamics/fatigue/effort_perception.py
- bioptim/dynamics/fatigue/fatigue_dynamics.py
- bioptim/dynamics/fatigue/michaud_fatigue.py
- bioptim/dynamics/fatigue/muscle_fatigue.py
- bioptim/dynamics/fatigue/tau_fatigue.py
- bioptim/dynamics/fatigue/xia_fatigue.py
- bioptim/misc/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/542)
> Added the capability to apply fatigue directly to joint torque

- bioptim/gui/graph.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/552)
> [RTR] Issue#550 correction

- bioptim/examples/getting_started/pendulum.py
- bioptim/optimization/solution.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/566)
> Allowed for bioviz 2.2.0 as the changes don't impact bioptim

- .github/workflows/run_tests.yml
- bioptim/examples/sqp_method/pendulum.py
- tests/test_global_sqp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/569)
> [RTM] SQP test

- bioptim/interfaces/solve_ivp_interface.py
- bioptim/optimization/solution.py
fixing the tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/590)
> [RTR] updating to numpy 1.24

- bioptim/limits/path_conditions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/599)
> Partly addressing QandQdotBounds Issues

- bioptim/limits/constraints.py
- bioptim/limits/multinode_constraint.py
- bioptim/limits/objective_functions.py
- bioptim/limits/penalty_option.py
- bioptim/optimization/parameters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/600)
> Changed name of clear_penalty to ensure_penalty_sanity

- bioptim/interfaces/biorbd_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/608)
> Fixed the versions

- bioptim/optimization/solution.py
When animating the solution it was crashing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/611)
> Correct bug with bioviz version

- bioptim/examples/getting_started/example_external_forces.py
- bioptim/optimization/optimal_control_program.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/612)
> [RTM] Removed an occurrence of nb_q

- bioptim/dynamics/configure_problem.py
- tests/test_dynamics.py
Addressing #429
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/629)
> [RTRT] Addressing a small issue.

- bioptim/dynamics/configure_problem.py
- bioptim/examples/symmetrical_torque_driven_ocp/symmetry_by_mapping.py
- bioptim/interfaces/biorbd_model.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/639)
> [RTR] Reverted the default behavior of copying the mappings

- bioptim/examples/getting_started/example_multistart.py
- bioptim/optimization/multi_start.py
- tests/test_global_getting_started.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/634)
> [RTM] New multi-start debug options

- README.md
look at this nice documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/656)
> troubleshoot DOCUMENTATION

- bioptim/dynamics/dynamics_functions.py
- bioptim/dynamics/integrator.py
- bioptim/interfaces/biomodel.py
- bioptim/interfaces/biorbd_model.py
- tests/test_biorbd_model.py
- tests/test_biorbd_multi_model.py
Small refactor, everything looks cleaner, and better looking to track potential bugs.
Also spots some errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/662)
> [RTR] Maintain biorbdModel and MultiBiorbdModel health

- bioptim/dynamics/configure_problem.py
- bioptim/dynamics/dynamics_functions.py
- bioptim/examples/getting_started/pendulum.py
- bioptim/examples/muscle_driven_ocp/muscle_activations_tracker.py
- bioptim/examples/muscle_driven_ocp/muscle_excitations_tracker.py
- bioptim/gui/check_conditioning.py
- bioptim/gui/graph.py
- bioptim/gui/plot.py
- bioptim/interfaces/acados_interface.py
- bioptim/interfaces/interface_utils.py
- bioptim/limits/penalty.py
- bioptim/limits/penalty_option.py
- bioptim/optimization/non_linear_program.py
- bioptim/optimization/optimal_control_program.py
- bioptim/optimization/optimization_variable.py
- bioptim/optimization/optimization_vector.py
- bioptim/optimization/parameters.py
- bioptim/optimization/solution.py
- tests/test__global_plots.py
- tests/test_acados_interface.py
- tests/test_dynamics.py
- tests/test_global_fail.py
- tests/test_global_minimize_marker_velocity.py
- tests/test_graph.py
- tests/test_ligaments.py
- tests/test_passive_torque.py
- tests/test_penalty.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/674)
> Fixed parameters when assume_phase_dynamics is False

- bioptim/gui/plot.py
Restoring the feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/702)
> [RTR] fix on live optimization

- bioptim/interfaces/solver_options.py
- tests/test_solver_options.py
fixing solver ipopt options methods. adressing #706 @EveCharbie
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/709)
> [RTM] Ipopt options were problematic

- .github/workflows/run_tests_linux.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/740)
> change way to report coverage

- bioptim/interfaces/biorbd_model.py
- tests/shard1/test_biorbd_multi_model.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/757)
> [RTR] extra models for futher computations

- bioptim/limits/path_conditions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/760)
> [RTR] tiny commit to help everyone debugging

- tests/shard6/test_unit.py
Testing these helpers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/764)
> [RTR] Unit test on helper function.

- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/774)
> Update README.md with PhaseDynamics instead of assume_phase_dynamics

- bioptim/limits/penalty_option.py
- tests/shard6/test_get_u.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/775)
> get_u isolated as a helper+ unit test

- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/777)
> [RTR] removing assume_phase from readme

- bioptim/optimization/solution.py
From  https://github.com/Ipuch/bioptim/pull/8#pullrequestreview-1705029154
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/786)
> Minibug patch

- tests/shard6/test_unit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/785)
> some unit test in integration for stability purpose.

- bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py
- tests/shard1/test_all_examples.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/798)
> [RTR] Udpate min max + test

- bioptim/interfaces/interface_utils.py
- tests/shard6/test_unit_solver_interface.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/793)
> [RTR] Refactoring solver interface utils for the better

- bioptim/examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py
- bioptim/optimization/variational_optimal_control_program.py
Just docstring for mickael, no conflict with benjamin i promise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/811)
> [RTM] Commit for mickael

- bioptim/examples/getting_started/example_external_forces.py
- tests/shard1/test_no_control.py
- tests/shard6/test_integrators.py
- tests/shard6/test_integrators_for_sctochastic.py
- tests/shard6/test_time_dependent_problems.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/828)
> [Version 3.1] Additional tests for the integration of time dependent or stochastics problems

- bioptim/limits/path_conditions.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/837)
> [Version 3.1] Fix self[phase] in path condition

- bioptim/limits/penalty.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/834)
> [RTR] fix key in minimize parameters -tests/examples will be created afterwards

- bioptim/examples/holonomic_constraints/two_pendulums.py
Error in vector size
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/849)
> Fixing Lagrange multipliers plotting

- bioptim/dynamics/integrator.py
- bioptim/gui/plot.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/850)
> Correcting RK4 and RK8 time integration calculation

- bioptim/gui/online_callback.py
- bioptim/gui/plot.py
- bioptim/interfaces/interface_utils.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/855)
> [RTR] refactor(maintaining plots)

- bioptim/models/biorbd/holonomic_biorbd_model.py
- tests/shard1/test_biorbd_model_holonomic.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/854)
> [RTM when tests pass] Extra checks in holonomic model

- bioptim/limits/path_conditions.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/860)
> [RTM when test passes] Fix self[phase] in path condition

- bioptim/models/biorbd/biorbd_model.py
I have a strong belief, that we should pass a bimapping instead of catching "_joint", or "_root" ?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/862)
> [RTR] bounds in model clarified

- bioptim/examples/getting_started/pendulum.py
- bioptim/gui/ipopt_output_plot.py
- bioptim/gui/plot.py
- bioptim/optimization/optimal_control_program.py
- tests/shard1/test__global_plots.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/871)
> [RTR] Save IPOPT output

- bioptim/dynamics/configure_problem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/878)
> docs: scoot numerical_time_series

- .github/workflows/run_tests_osx_win.yml
- bioptim/dynamics/configure_new_variable.py
- bioptim/examples/getting_started/example_multinode_constraints.py
- bioptim/gui/plot.py
- bioptim/interfaces/acados_interface.py
- bioptim/limits/constraints.py
- bioptim/limits/multinode_penalty.py
- bioptim/limits/penalty_option.py
- bioptim/limits/phase_transition.py
- bioptim/models/biorbd/multi_biorbd_model.py
- bioptim/models/protocols/biomodel.py
- bioptim/models/utils.py
- bioptim/optimization/optimization_variable.py
- bioptim/optimization/solution/solution.py
- environment.yml
- external/acados_install_linux.sh
- external/acados_install_mac.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/880)
> Fixed ACADOS for Macos

- bioptim/dynamics/configure_problem.py
- bioptim/examples/holonomic_constraints/two_pendulums.py
- bioptim/gui/plot.py
- bioptim/models/biorbd/holonomic_biorbd_model.py
- tests/shard1/test_biorbd_model_holonomic.py
This should help you in a near future: @AnaisFarr, @SamHybz, @Kev1CO 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/884)
> [RTR] graphs: fix the holonomic case

- README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/897)
> Testing the tests on windows

- bioptim/examples/moving_horizon_estimation/multi_cyclic_nmpc_with_parameters.py
- bioptim/models/utils.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/902)
> refactor: check mapping dof (cleaning on the fly)

- README.md
When the user does not choose a correct partition, we recommend one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/906)
> feat: alternative partition recommendation

- bioptim/limits/objective_functions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/904)
> Minimize_contact_force in objectives.

- bioptim/dynamics/configure_problem.py
- bioptim/dynamics/dynamics_functions.py
- bioptim/models/biorbd/biorbd_model.py
- bioptim/models/biorbd/holonomic_biorbd_model.py
@pariterre and @EveCharbie if any of you can review asynchronously, it will be fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/919)
> feat: holonomic torque driven can friction too

- bioptim/dynamics/configure_new_variable.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/922)
> [RTR] Fixing some TODOs

- bioptim/optimization/non_linear_program.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/924)
> [RTR] refactor: retrieve_force

- bioptim/models/biorbd/holonomic_biorbd_model.py
- bioptim/models/protocols/holonomic_biomodel.py
- tests/shard1/test_biorbd_model_holonomic.py
Trying to reduce size of the PR :
- #907 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/925)
> [RTR] feat: autopartition for holonomic models

- .github/workflows/run_tests_linux.yml
- tests/shard3/test_global_getting_started.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/941)
> [RTR] Memory and execution time tests (before refactor)

- bioptim/misc/parameters_types.py
- bioptim/models/biorbd/biorbd_model.py
- bioptim/models/biorbd/external_forces.py
- bioptim/models/biorbd/holonomic_biorbd_model.py
- bioptim/models/biorbd/multi_biorbd_model.py
- bioptim/models/biorbd/stochastic_biorbd_model.py
- bioptim/models/biorbd/variational_biorbd_model.py
- bioptim/models/biorbd/viewer_bioviz.py
- bioptim/models/biorbd/viewer_pyorerun.py
- bioptim/models/biorbd/viewer_utils.py
https://github.com/pyomeca/bioptim/issues/927
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/951)
> [RTM] Annotated biorbd

- bioptim/gui/graph.py
- bioptim/gui/plot.py
- bioptim/misc/mapping.py
- bioptim/misc/parameters_types.py
- bioptim/models/biorbd/external_forces.py
- bioptim/models/protocols/biomodel.py
- bioptim/models/protocols/holonomic_biomodel.py
- bioptim/models/protocols/stochastic_biomodel.py
- bioptim/models/protocols/variational_biomodel.py
https://github.com/pyomeca/bioptim/issues/927
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/963)
> Converted protocols package to use new type hints

- .github/workflows/run_tests_linux.yml
- .github/workflows/run_tests_osx_win.yml
- bioptim/interfaces/abstract_options.py
- bioptim/interfaces/acados_interface.py
- bioptim/interfaces/acados_options.py
- bioptim/interfaces/interface_utils.py
- bioptim/interfaces/ipopt_interface.py
- bioptim/interfaces/ipopt_options.py
- bioptim/interfaces/solve_ivp_interface.py
- bioptim/interfaces/solver_interface.py
- bioptim/interfaces/sqp_interface.py
- bioptim/interfaces/sqp_options.py
- bioptim/misc/parameters_types.py
- environment.yml
https://github.com/pyomeca/bioptim/issues/927
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/972)
> [RTR]Convert interfaces

- bioptim/gui/serializable_class.py
Serializes the ODE solver within the `NlpSerializable` class.
This ensures that the ODE solver is properly saved and loaded when serializing and deserializing `Nlp` objects,
which is necessary to support server live plots.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/985)
> Serializes ODE Solver in NlpSerializable

- bioptim/gui/plot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/988)
> Smaller marker size because I do not see anything XD 

- tests/shard6/test_time_dependent_custom_model.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/1000)
> Removing obsolete constraint from time dependent test

- tests/shard3/test_global_getting_started.py
- tests/shard3/test_passive_torque.py
- tests/shard6/test_vector_layout.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/1016)
> be more lax on github action maximum time

- bioptim/examples/utils.py
- tests/shard1/test_continuity_as_objective.py
- tests/shard2/test_global_nmpc_final.py
- tests/shard4/test_penalty.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/1026)
> Added a static_property to folder

- bioptim/examples/getting_started/basic_ocp.py
- bioptim/interfaces/interface_utils.py
- bioptim/interfaces/solver_interface.py
- bioptim/optimization/optimal_control_program.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/1017)
> [RTM when tests pass] Added the capability to skip shake_tree if problem did not change

- bioptim/__init__.py
- bioptim/dynamics/integrator.py
- bioptim/examples/toy_examples/moving_horizon_estimation/mhe.py
- bioptim/examples/toy_examples/moving_horizon_estimation/multi_cyclic_nmpc_with_parameters.py
- bioptim/examples/toy_examples/torque_driven_ocp/minimize_maximum_torque_by_extra_parameter.py
- bioptim/examples/toy_examples/torque_driven_ocp/minmax_torque_by_extra_parameter_multiphase.py
- bioptim/models/biorbd/biorbd_model.py
- environment.yml
- tests/shard1/test_biorbd_model.py
- tests/shard1/test_biorbd_multi_model.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/1027)
> Allowed for biorbd=1.12
